project: add docker stack
SnaKyEyeS/ADE-Scheduler pull request #1049
Opened 2024-05-24 07:48 UTC by lauren-d

* Adds docker service for development stack.
* Adds scripts to manage instance.
* Bumps dependencies.
* Updates .gitignore.
* Removes useless import.
* Adds script to launch tests.

2024-05-24 17:43 UTC, jeertmans reviewed
Nice work! I guess this isn't all done, but I left a few comments :-)

2024-05-27 07:42 UTC, lauren-d commented on docker-compose.yml
Yes of course, it's planned.

2024-05-27 07:45 UTC, lauren-d commented on pyproject.toml
> +python = ">= 3.9, <3.10"
Yes, I have temporarily fixed the python version. There are no constraints but I think that to ensure the application works correctly in higher versions, more testing is needed.
Once the tests are written, we could set up a Github workflow to test higher versions and release/update the constraint.

2024-05-27 11:34 UTC, jeertmans commented on pyproject.toml
> +python = ">= 3.9, <3.10"
Sure, this is just that 3.9 is relatively old, so in one year or two we might need to bump the minimal version.

Linters like Ruff are very good at catching code that works on some Python versions but not all (and it reads `pyproject.toml` to know which version your project targets). The only issue is that we might need to opt out of Poetry because it is not compliant with [PEP 621](https://www.python.org/dev/peps/pep-0621), and use something like PDM or even Rye (very recent, but much faster at resolving dependencies conflicts).

2024-06-10 15:16 UTC, jeertmans commented
Hello @lauren-d, do you think you could avoid squashing all the commits? This makes it hard for me to review new changes versus changes I already reviewed.

GitHub allows squashing all the commits before merging, so this is not an issue if you have plenty of commits for the PR :-)

2024-06-12 07:35 UTC, lauren-d commented
Hello @jeertmans , I understand that it is difficult to follow 😅.
In fact, you don't have to do the review yet.

The PR is in draft status. Normally, this means that it is not yet ready for review.

As soon as it's ready, I'll call for a review.

2024-06-18 14:19 UTC, jeertmans requested changes
Hello @lauren-d, thanks for your work on this!

I left a few comments within the code, please take your time :-)

Moreover, I think this would be great if we could upload code-coverage, but I am not sure this is supported by the community version of CodeCov.io...

2024-06-18 14:19 UTC, jeertmans commented on .pre-commit-config.yaml
> +    args: [--autofix, --indent, '2']
I would suggest only using Ruff (in place of black, isort and flake8), and configure all of them inside the `pyproject.toml` file. This tool runs much faster and will reduce the number of configuration files we need.

You can see examples from my other project:
https://github.com/jeertmans/DiffeRT/blob/13f067ff3afb068da2b692cfe692e62bdcfdb33b/.pre-commit-config.yaml#L18-L25 and
https://github.com/jeertmans/DiffeRT/blob/13f067ff3afb068da2b692cfe692e62bdcfdb33b/pyproject.toml#L90-L118

2024-06-18 14:19 UTC, jeertmans commented on docs/source/conf.py
>  sys.path.insert(0, os.path.abspath("../../backend"))
Those should not be needed anymore (because Poetry install local packages in Python environment).
```suggestion
```

2024-06-18 14:19 UTC, jeertmans commented on pyproject.toml
> +isort = "^5.13.2"
```suggestion
```

To be removed if we use Ruff

2024-06-18 14:19 UTC, jeertmans commented on pyproject.toml
> +pydocstyle = "^6.3.0"
```suggestion
```

To be removed if we use ruff.

Also, I think those dependencies should be dev dependencies.

2024-06-18 14:19 UTC, jeertmans commented on pytest.ini
I would prefer using `pytest-env` (and others) and put the configuration inside `pyproject.toml`. E.g.: https://github.com/jeertmans/DiffeRT/blob/13f067ff3afb068da2b692cfe692e62bdcfdb33b/pyproject.toml#L68-L88

2024-06-18 14:19 UTC, jeertmans commented on static/json/geo_locations.json
Just curious: how did you update?

2024-06-18 14:19 UTC, jeertmans commented on tests/conftest.py
>  sys.path.append(os.getcwd())
Unsure this is needed if we use `pytest-env`, to be checked

2024-06-18 15:06 UTC, lauren-d commented on static/json/geo_locations.json
I didn't update the data. It just a automatic correction from a json formatter.

2024-06-18 15:08 UTC, lauren-d commented on docs/source/conf.py
>  sys.path.insert(0, os.path.abspath("../../backend"))
ok, I will remove it

2024-06-19 06:56 UTC, lauren-d commented on .github/workflows/ci.yml
> +      uses: snok/install-poetry@v1
Thanks for the tip

2024-06-19 07:09 UTC, lauren-d commented
@jeertmans, I tested and configured Ruff locally. There are 669 errors to correct.
I suggest creating a new pull request to implement Ruff and fix all the code to pass the tests.

2024-06-19 07:11 UTC, lauren-d commented on pyproject.toml
> +pydocstyle = "^6.3.0"
see general comment

2024-06-19 07:11 UTC, lauren-d commented on pyproject.toml
> +isort = "^5.13.2"
see general comment

2024-06-19 07:12 UTC, lauren-d commented on .pre-commit-config.yaml
> +    args: [--autofix, --indent, '2']
see general comment

2024-06-19 07:13 UTC, lauren-d commented on .pre-commit-config.yaml
> +#    additional_dependencies: [types-requests, types-setuptools]
see general comment

2024-06-19 07:28 UTC, lauren-d commented on pytest.ini
I put config in pyproject.tml

2024-06-19 07:29 UTC, lauren-d commented on pyproject.toml
> +pydocstyle = "^6.3.0"
I moved to dev dependencies

2024-06-19 07:41 UTC, lauren-d commented on tests/conftest.py
>  sys.path.append(os.getcwd())
I think we can keep it.
Maybe we want to store some environment variables locally

2024-06-19 08:18 UTC, jeertmans commented
> Hello @jeertmans, I tested and configured Ruff locally. There are 669 errors to correct. I suggest creating a new pull request to implement Ruff, pyright and fix all the code to pass the tests.

Let’s me give it a try myself, I will do that later or tomorrow. I think I can setup a Ruff config with no error, and we can enforce stricter rules in a future PR

2024-06-19 12:08 UTC, jeertmans commented
@lauren-d I have added Ruff config, removed the old ones (because Ruff replaces flake, isort, black, and pydocstyle), and finally fixed the 

One important note: the `utf-8` preamble is one of the legacy thing from Python 2 that are not needed anymore, see https://peps.python.org/pep-3120/.

2024-06-19 13:31 UTC, lauren-d commented
@jeertmans Thank you for your help!

I'm not totally familiar with pre-commit and ruff yet ( I'm also allergic to auto-fix features. I shall do my best 😅) . 

If it's ok for you, could you approve this PR?

2024-06-19 14:04 UTC, jeertmans commented
> @jeertmans Thank you for your help!
> 
> I'm not totally familiar with pre-commit and ruff yet ( I'm also allergic to auto-fix features. I shall do my best 😅) .
> 
> If it's ok for you, could you approve this PR?

I can understand that you may feel uncomfortable using an auto fix (which can be disabled), but those tool have become so good, fast, and reliable that I usually trust them blindly (especially as I can review the auto fix commits anyway). And because of the code formatter, performing fixes manually usually will give the result code as using the auto fix.

Looks great to me, so let’s go!

2024-06-19 14:05 UTC, jeertmans approved these changes

2024-06-19 14:05 UTC, merged