#Issue:Confusing naming of Flask endpoints solution
SnaKyEyeS/ADE-Scheduler pull request #312
Opened 2021-01-18 16:27 UTC by raftar2097

2021-01-18 16:30 UTC, SnaKyEyeS commented
Thanks for the contribution ! However, you also need to change the methods name in the `calendar.js` file for this to work.

2021-01-18 16:34 UTC, jeertmans commented
Yes and the tests in `/tests/view/test_calendar.py` should also be updated then :) @raftar2097

2021-01-18 16:44 UTC, raftar2097 commented
@jeertmans  done that for test also

2021-01-18 16:55 UTC, raftar2097 commented
@jeertmans  anything more needs to be done

2021-01-18 17:03 UTC, jeertmans commented
@raftar2097 yes, as pointed out by @SnaKyEyeS , the file `static/js/calendar.js` has to be edited the same way, to reflect the changes you did in the Python files. After that I think it will be done, thanks !

2021-01-18 17:32 UTC, jeertmans requested changes

2021-01-18 17:32 UTC, jeertmans commented on tests/views/test_calendar.py
> +    rv = client.patch(
Actually you have mistaken `calendar.update_custom_event` with `calendar.add_custom_event`

2021-01-18 17:39 UTC, raftar2097 commented
Will look into it and get back to you

On Mon, 18 Jan, 2021, 11:02 pm Jérome Eertmans, <notifications@github.com>
wrote:

> *@jeertmans* requested changes on this pull request.
> ------------------------------
>
> In tests/views/test_calendar.py
> <https://github.com/SnaKyEyeS/ADE-Scheduler/pull/312#discussion_r559716203>
> :
>
> > @@ -347,7 +347,7 @@ def test_update_custom_event(client, user):
>      param = {**changes, **dict(schedule_number=0, color="Color")}
>
>      # Test non-recurring event
> -    rv = client.post(
> +    rv = client.patch(
>
> Actually you have mistaken calendar.update_custom_event with
> calendar.add_custom_event
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/SnaKyEyeS/ADE-Scheduler/pull/312#pullrequestreview-570683266>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGLBFGDRLEP4HVJHTZVB3ULS2RWD3ANCNFSM4WHRKYLA>
> .
>

2021-02-04 14:11 UTC, jeertmans commented
Hello @raftar2097, are you still working on this ?

2021-02-27 09:58 UTC, closed without merging